version: '3.8'

services:
  app:
    build: .
    container_name: beanpon_messenger
    restart: always
    ports:
      - "10.10.0.5:5082:5082"
    environment:
      - ENV=production
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge